version: "3.8"

services:
  app:
    build: ./app
    container_name: cloudvision_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - minio
    environment:
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123

  worker:
    build: ./worker
    container_name: cloudvision_worker
    depends_on:
      - redis
      - minio
    environment:
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123

  redis:
    image: redis:alpine
    container_name: cloudvision_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: cloudvision_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio_data:/data

volumes:
  minio_data:
