name: CI - CloudVision Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Use Docker Compose Action
        uses: docker/compose-action@v2.0.0
        with:
          compose-file: docker-compose.yml
          run: build

